[package]
name = "medusa_lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.6"
pest_derive = "2.7.6"
regex = "1.10.5"
stdext = "0.3.3"
winreg = "0.52.0"

